-- Portfolio V5 - Supabase Postgres schema
--
-- How to use:
-- 1) Create a Supabase project (name suggestion: portofolio-v5)
-- 2) Supabase Dashboard → SQL Editor → paste/run this file (run once)
--
-- Notes:
-- - Supabase's underlying database name is typically "postgres".
-- - This script creates tables in the default schema: public.

-- ============================
-- TABLES
-- ============================
CREATE TABLE public.projects (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text,
  description text,
  img text,
  link text,
  github text,
  features jsonb,
  tech_stack jsonb,
  is_published boolean DEFAULT true,
  order_index int DEFAULT 0,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE public.certificates (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  img text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE public.portfolio_comments (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  content text NOT NULL,
  user_name text NOT NULL,
  profile_image text,
  is_pinned boolean DEFAULT false,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE public.profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  username text UNIQUE NOT NULL,
  role text NOT NULL CHECK (role IN ('admin', 'user')),
  created_at timestamptz DEFAULT now()
);

-- ============================
-- RLS
-- ============================
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.certificates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.portfolio_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "public read projects"
ON public.projects FOR SELECT USING (true);

CREATE POLICY "public read certificates"
ON public.certificates FOR SELECT USING (true);

CREATE POLICY "public read comments"
ON public.portfolio_comments FOR SELECT USING (true);

CREATE POLICY "public insert comment"
ON public.portfolio_comments FOR INSERT
WITH CHECK (is_pinned = false);

CREATE POLICY "users read own profile"
ON public.profiles FOR SELECT
USING (auth.uid() = id);

CREATE POLICY "admin manage projects"
ON public.projects FOR ALL
USING (
  EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid() AND role = 'admin'
  )
);

CREATE POLICY "admin manage certificates"
ON public.certificates FOR ALL
USING (
  EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid() AND role = 'admin'
  )
);

CREATE POLICY "admin update comments"
ON public.portfolio_comments FOR UPDATE
USING (
  EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid() AND role = 'admin'
  )
);

CREATE POLICY "admin delete comments"
ON public.portfolio_comments FOR DELETE
USING (
  EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid() AND role = 'admin'
  )
);

-- ============================
-- STORAGE
-- ============================
INSERT INTO storage.buckets (id, name, public)
VALUES ('project-images', 'project-images', true)
ON CONFLICT DO NOTHING;

CREATE POLICY "admin upload project images"
ON storage.objects FOR INSERT
WITH CHECK (
  bucket_id = 'project-images'
  AND EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid() AND role = 'admin'
  )
);

CREATE POLICY "public read project images"
ON storage.objects FOR SELECT
USING (bucket_id = 'project-images');

INSERT INTO storage.buckets (id, name, public)
VALUES ('certificate-images', 'certificate-images', true)
ON CONFLICT DO NOTHING;

CREATE POLICY "admin upload certificate images"
ON storage.objects FOR INSERT
WITH CHECK (
  bucket_id = 'certificate-images'
  AND EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid() AND role = 'admin'
  )
);

CREATE POLICY "public read certificate images"
ON storage.objects FOR SELECT
USING (bucket_id = 'certificate-images');

-- ============================
-- CMS CONTENT TABLES
-- ============================

-- Key-value store for page content (about, home, etc.)
CREATE TABLE public.site_content (
  id text PRIMARY KEY,
  data jsonb NOT NULL DEFAULT '{}',
  updated_at timestamptz DEFAULT now()
);

-- Dynamic tech stacks
CREATE TABLE public.tech_stacks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  icon text,
  language text NOT NULL,
  order_index int DEFAULT 0,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE public.site_content ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tech_stacks ENABLE ROW LEVEL SECURITY;

CREATE POLICY "public read site_content"
ON public.site_content FOR SELECT USING (true);

CREATE POLICY "admin manage site_content"
ON public.site_content FOR ALL
USING (
  EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid() AND role = 'admin'
  )
);

CREATE POLICY "public read tech_stacks"
ON public.tech_stacks FOR SELECT USING (true);

CREATE POLICY "admin manage tech_stacks"
ON public.tech_stacks FOR ALL
USING (
  EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid() AND role = 'admin'
  )
);

-- Storage bucket for site images (about photo, hero image, tech icons, etc.)
INSERT INTO storage.buckets (id, name, public)
VALUES ('site-images', 'site-images', true)
ON CONFLICT DO NOTHING;

CREATE POLICY "admin upload site images"
ON storage.objects FOR INSERT
WITH CHECK (
  bucket_id = 'site-images'
  AND EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid() AND role = 'admin'
  )
);

CREATE POLICY "public read site images"
ON storage.objects FOR SELECT
USING (bucket_id = 'site-images');

CREATE POLICY "admin delete site images"
ON storage.objects FOR DELETE
USING (
  bucket_id = 'site-images'
  AND EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid() AND role = 'admin'
  )
);

-- Seed default content
INSERT INTO public.site_content (id, data) VALUES
('home', '{
  "title_line1": "Frontend",
  "title_line2": "Developer",
  "typing_words": ["Network & Telecom Student", "Tech Enthusiast"],
  "description": "Menciptakan Website Yang Inovatif, Fungsional, dan User-Friendly untuk Solusi Digital.",
  "tech_badges": ["React", "Javascript", "Node.js", "Tailwind"],
  "hero_image": "/Animation1.gif",
  "status_badge": "Ready to Innovate"
}'::jsonb),
('about', '{
  "name": "raihan fathan",
  "subtitle": "Hello, I''m",
  "description": "Saya adalah mahasiswa Teknik Informatika yang berfokus pada pengembangan Front-End. Saya berfokus pada penciptaan pengalaman digital yang menarik dan selalu berupaya memberikan solusi terbaik dalam setiap proyek yang saya kerjakan.",
  "quote": "Leveraging AI as a professional tool, not a replacement.",
  "photo_url": "/Photo.jpg",
  "cv_url": "https://drive.google.com/drive/folders/1BOm51Grsabb3zj6Xk27K-iRwI1zITcpo",
  "experience_start": "2021-11-06",
  "social_links": [
    {"type": "github", "url": "https://github.com/rhnfthn"},
    {"type": "linkedin", "url": "https://www.linkedin.com/in/raihanfathan/"},
    {"type": "instagram", "url": "https://www.instagram.com/rhn_fthn/?hl=id"}
  ]
}'::jsonb)
ON CONFLICT DO NOTHING;

-- Seed default tech stacks
INSERT INTO public.tech_stacks (icon, language, order_index) VALUES
('/html.svg', 'HTML', 1),
('/css.svg', 'CSS', 2),
('/javascript.svg', 'JavaScript', 3),
('/tailwind.svg', 'Tailwind CSS', 4),
('/reactjs.svg', 'ReactJS', 5),
('/vite.svg', 'Vite', 6),
('/nodejs.svg', 'Node JS', 7),
('/bootstrap.svg', 'Bootstrap', 8),
('/firebase.svg', 'Firebase', 9),
('/MUI.svg', 'Material UI', 10),
('/vercel.svg', 'Vercel', 11),
('/SweetAlert.svg', 'SweetAlert2', 12)
ON CONFLICT DO NOTHING;
